application: land-rush
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: numpy
  version: "1.6.1"

builtins:
- deferred: on
- remote_api: on
